# Stage 1: Build the Go binary
FROM golang:latest AS builder

# Set the working directory inside the container
WORKDIR /docker_wd

# Copy the go.mod and go.sum files to download dependencies
# Copying these files separately allows Docker to cache the downloaded modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code into the container
COPY . .

# Set the build argument for the environment
ARG APP_ENV
ENV APP_ENV=${APP_ENV}

# Run the tests directly when the container starts using the environment variable
# @TODO: Explore `integration-test-coverage-issue` branch
ENTRYPOINT ["sh", "-c", \
    "echo Running test in APP_ENV=${APP_ENV} && \
    APP_ENV=${APP_ENV} go test ./... -coverprofile=coverage.out && \
    go tool cover -html=coverage.out -o /docker_wd/test/reports/coverage.html"]